### ISSUE TITLE
[HIPIFY] How to estimate the accuracy of converting HIP to CUDA or converting CUDA to HIP?

### ISSUE THREAD

**Issue by NiuKeke** [ROCm-Developer-Tools/HIPIFY#1113]
How to estimate the accuracy of converting HIP to CUDA or converting CUDA to HIP? As we all know, HIP could support CUDA definitely.But how to estimate its support accuracy,which is important to using HIP.Is there some tool which could fix this problem?

**Comment by emankov** [comment]
HIPIFY tools convert CUDA into HIP, not vice versa. The accuracy of the successfully hipified code can be estimated by compiling it either for AMD or NVIDIA target, and then by running the successfully compiled binary on the target.

**Comment by emankov** [comment]
Close as answered
