### ISSUE TITLE
[HIPIFY] Makefile generation

### ISSUE THREAD

**Issue by alvin546** [ROCm-Developer-Tools/HIPIFY#1132]
Is there any option available to migrate or generate Makefile/build file in hipify-clang?

**Comment by emankov** [comment]
Could you provide us with more details on what you mean by "migrate or generate" Makefile/build, please?

**Comment by alvin546** [comment]
I am currently engaged in a project that comprises over 100 files. While attempting to migrate it using HIPIFY, I've observed that the tool exclusively recognizes .cu files for conversion. Consequently, I find myself responsible for independently crafting a Makefile to facilitate the compilation of these files. Could you please clarify whether HIPIFY supports the automatic generation of Makefiles to streamline this process?

**Comment by emankov** [comment]
Which HIPIFY tool were you using?

**Comment by alvin546** [comment]
I'm using [this](https://github.com/ROCm-Developer-Tools/HIPIFY/blob/amd-staging/docs/hipify-clang.md#hipify-clang-usage)

**Comment by emankov** [comment]
Hello, @alvin546,

First, sorry for the delayed answer.

> While attempting to migrate it using HIPIFY, I've observed that the tool exclusively recognizes .cu files for conversion.

It is not so. Both `hipify-clang` and `hipify-perl` can hipify any files despite their extensions.

Are you using some additional scripts on top of hipify-clang?

> Could you please clarify whether HIPIFY supports the automatic generation of Makefiles to streamline this process?

HIPIFY tools can only accomplish a source-to-source translation of the CUDA files into HIP files. Multiple source files are also supported. You can also provide a compilation database `compile_commands.json` for your hipification. Additionally, hipify-clang is able to generate `hipify-perl` and `CUDA2HIP` documentation, but not `build` files.

**Comment by emankov** [comment]
Closed as answered.
