### ISSUE TITLE
[HIPIFY] Cuda graph

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIPIFY#1197]
Could you please suggest how to hipify cuda graph APIs ? Thanks.

**Comment by emankov** [comment]
As usual. CUDA Graph APIs, both Driver and Runtime, are partially supported by ROCm HIP and HIPIFY tools. The currently supported and unsupported Graph APIs can be seen here:
https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/tables/CUDA_Driver_API_functions_supported_by_HIP.md#24-graph-management
and here:
https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/tables/CUDA_Runtime_API_functions_supported_by_HIP.md#28-graph-management

**Comment by oscarbg** [comment]
interested in cuda graphs conditional nodes.. let's see when it ships in ROCM..
