### ISSUE TITLE
[HIPIFY][BLAS] cublasSetMathMode and CUBLAS_GEMM_DEFAULT_TENSOR_OP

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIPIFY#1225]
Migrating a cuda program with /usr/bin/hipconvertinplace-perl.sh shows the following message.  Thanks for your suggestions on the migration. 

  warning: mixed_gemm.c:158: unsupported identifier "cublasSetMathMode"
  warning: mixed_gemm.c:158: unsupported identifier "CUBLAS_PEDANTIC_MATH"
  warning: mixed_gemm.c:244: unsupported identifier "CUBLAS_GEMM_DEFAULT_TENSOR_OP"
  warning: mixed_gemm.c:286: unsupported identifier "CUBLAS_GEMM_DEFAULT_TENSOR_OP"

The cuda program is https://github.com/pedrovalerolara/TF32-TF64/src

**Comment by emankov** [comment]
Hello @jinz2014,

It is because those identifiers (APIs and data types) are not yet supported by `hipBLAS`, unfortunately. We will let you know about it in this ticket once it happens.

Thanks,
Evgeny
