### ISSUE TITLE
[HIPIFY] Errors when processing the NVIDIA sample "simpleCubemapTexture"

### ISSUE THREAD

**Issue by wuren2020** [ROCm-Developer-Tools/HIPIFY#134]
Using HIPIFY to process the _simpleCubemapTexture_ example shipped in the CUDA 10.2 toolkit (commands: `cd /path/to/NVIDIA_CUDA-10.2_Samples/0_Simple/simpleCubemapTexture; hipify-clang simpleCubemapTexture.cu -- -I/path/to/NVIDIA_CUDA-10.2_Samples/common/inc`) produces the following error:
```
warning: Unknown CUDA version 10.2. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
In file included from <built-in>:1:
In file included from /usr/lib/llvm-11/lib/clang/11.0.0/include/__clang_cuda_runtime_wrapper.h:333:
/usr/local/cuda-10.2/include/texture_indirect_functions.h:218:3: error: use of undeclared identifier '__nv_tex_surf_handler'
  __nv_tex_surf_handler("__itexCubemap", ptr, obj, x, y, z);
  ^
/usr/local/cuda-10.2/include/texture_indirect_functions.h:228:3: note: in instantiation of function template specialization 'texCubemap<float>' requested here
  texCubemap(&ret, texObject, x, y, z);
  ^
/tmp/simpleCubemapTexture.cu-edba05.hip:104:52: note: in instantiation of function template specialization 'texCubemap<float>' requested here
        g_odata[face*width*width + y*width + x] = -texCubemap<float>(tex, cx, cy, cz);
                                                   ^
1 error generated when compiling for host.
Error while processing /tmp/simpleCubemapTexture.cu-edba05.hip.
```

Any thoughts will be appreciated.

**Comment by wuren2020** [comment]
Not sure if this is relevant, but also had issues with other samples as follows.

`hipify-clang 0_Simple/simpleSurfaceWrite/simpleSurfaceWrite.cu --skip-excluded-preprocessor-conditional-blocks  -- -I/path/to/NVIDIA_CUDA-10.2_Samples/common/inc`got the following error: 
```
warning: Unknown CUDA version 10.2. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
/tmp/simpleSurfaceWrite.cu-8cd6ee.hip:226:21: warning: CUDA identifier is deprecated.
    checkCudaErrors(cudaMemcpyToArray(cuArray,
                    ^
/tmp/simpleSurfaceWrite.cu-8cd6ee.hip:68:5: error: use of undeclared identifier 'surf2Dwrite'
    surf2Dwrite(gIData[y * width + x],
    ^
In file included from <built-in>:1:
In file included from /usr/lib/llvm-10/lib/clang/10.0.1/include/__clang_cuda_runtime_wrapper.h:324:
/usr/local/cuda-10.2/include/texture_indirect_functions.h:145:4: error: use of undeclared identifier '__nv_tex_surf_handler'
   __nv_tex_surf_handler("__itex2D", ptr, obj, x, y);
   ^
/usr/local/cuda-10.2/include/texture_indirect_functions.h:154:3: note: in instantiation of function template specialization 'tex2D<float>' requested here
  tex2D(&ret, texObject, x, y);
  ^
/tmp/simpleSurfaceWrite.cu-8cd6ee.hip:96:29: note: in instantiation of function template specialization 'tex2D<float>' requested here
    gOData[y * width + x] = tex2D<float>(tex, tu, tv);
                            ^
1 warning and 2 errors generated when compiling for host.
Error while processing /tmp/simpleSurfaceWrite.cu-8cd6ee.hip.
```
, and `hipify-clang 0_Simple/simpleMultiCopy/simpleMultiCopy.cu --skip-excluded-preprocessor-conditional-blocks  -- -I/path/to/NVIDIA_CUDA-10.2_Samples/common/inc` got
```
/tmp/simpleMultiCopy.cu-2fb81b.hip:128:7: error: no matching function for call to 'max'
      max((32.0f / (_ConvertSMVer2Cores(deviceProp.major, deviceProp.minor) *
...
...
/usr/local/cuda-10.2/include/crt/math_functions.hpp:1079:31: note: candidate function not viable: call to __device__ function from __host__ function
__MATH_FUNCTIONS_DECL__ float max(float a, float b)
```
even though __MATH_FUNCTIONS_DECL__ is defined as `__host__ __device__`.

**Comment by emankov** [comment]
@wuren2020, 
Could you, please, split this issue based on `CUDA SDK` sample name and the error reported? Thus, we shall see one issue per sample with the corresponding input command line and error log.

P.S.
Although supporting all `CUDA SDK` samples is not the first-class priority for `hipify-clang`, I agree, that we don't want to see clang compilation errors without a chance to hipify them in any way.

**Comment by zhangxi19920406** [comment]
For the origin issue (error output with "error: use of undeclared identifier '__nv_tex_surf_handler'")
I find many cases in CUDA samples:
eg: 
0_Simple
cudaNvSci/imageKernels.cu, simpleCubemapTexture/simpleCubemapTexture.cu, simpleLayeredTexture/simpleLayeredTexture.cu, simplePitchLinearTexture/simplePitchLinearTexture.cu, simpleSurfaceWrite/simpleSurfaceWrite.cu, simpleTexture/simpleTexture.cu, simpleTextureDrv/simpleTexture_kernel.cu,
2_Graphics
bindlessTexture/bindlessTexture_kernel.cu, simpleTexture3D/simpleTexture3D_kernel.cu, volumeFiltering/volumeFilter_kernel.cu, volumeRender/volumeRender_kernel.cu
....

Overall there are around 40 files have this issue
