### ISSUE TITLE
[HIPIFY] Processing NVIDIA samples, met issues when there is #if #endif

### ISSUE THREAD

**Issue by zhangxi19920406** [ROCm-Developer-Tools/HIPIFY#138]
Using HIPIFY working on many CUDA samples, it is trying to transform all the code inside `#if`, `#else`, and `#endif`. There are some headers `include <windows.h>` cant be read according to the platform.

e.g.
I am running `CUDA_samples/samples/2_Graphics/marchingCubes/marchingCubes.cpp`
`./hipify-clang ~/Project/CUDA_samples/samples/2_Graphics/marchingCubes/marchingCubes.cpp --cuda-path=/usr/local/cuda-10.2 --o-dir tests/CUDA_SAMPLES -I /usr/local/cuda-10.2/samples/common/inc/`

Met error:
`/tmp/marchingCubes.cpp-a31ae9.hip:70:12: fatal error: 'windows.h' file not found`
`#  include <windows.h>`
`           ^~~~~~~~~~~`
`28 warnings and 1 error generated when compiling for host.`

Line 67-71 in `marchingCubes.cpp`
`#if defined(WIN32) || defined(_WIN32) || defined(WIN64) || defined(_WIN64)`
`#  define WINDOWS_LEAN_AND_MEAN`
`#  define NOMINMAX`
`#  include <windows.h>`
`#endif`

**Comment by emankov** [comment]
Use `--skip-excluded-preprocessor-conditional-blocks` option for enabling default preprocessor behaviour by skipping undefined conditional blocks. Please, be aware that undefined conditional blocks will be left unhipified.

**Comment by emankov** [comment]
Close as answered.
