### ISSUE TITLE
[HIPIFY][build][LLVM] build fails, if multiple llvm/clang versions are installed

### ISSUE THREAD

**Issue by AngryLoki** [ROCm-Developer-Tools/HIPIFY#1396]
### Problem Description

Hi, I'm building HIPIFY 5.7.1 on Gentoo, and encountered an issue, which could be fixed here.

I have multiple LLVM/Clang versions installed, including 17.0.6 and 18.1.0.

And as https://github.com/ROCm/HIPIFY/blob/amd-staging/CMakeLists.txt#L35-L36 uses `find_package` without specifying version or range, CMake finds the latest version of LLVM, then build fails with `HipifyAction.cpp:1168:68: error: no viable conversion from 'const clang::FileEntry *' to 'FileEntryRef'` (which is expected). So I applied this patch to make 5.7.1 build work:
```patch
-  find_package(LLVM REQUIRED CONFIG PATHS ${CMAKE_PREFIX_PATH})
+  find_package(LLVM 17 REQUIRED CONFIG PATHS ${CMAKE_PREFIX_PATH})
```

Could you specify in later releases LLVM and Clang versions (or ranges) according to your [compatibility matrix](https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-clang.md#hipify-clang-dependencies) directly in find_package? Thanks!

### Operating System

Gentoo

### CPU

irrelevant

### ROCm Version

ROCm 5.7.1

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
Can the following suit your needs?

> Having not found or multiple LLVM instances, the root folder with LLVM distributive must be specified in the CMake command line to build hipify-clang, for example:

`-DCMAKE_PREFIX_PATH=/usr/llvm/17.0.6/dist`

https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-clang.md#hipify-clang-building

**Comment by AngryLoki** [comment]
@emankov , sorry, I missed this part in the readme and both of these solutions work:
```
-DCMAKE_PREFIX_PATH=/usr/lib/llvm/17/lib64/cmake/llvm
```
or
```
-DLLVM_DIR=/usr/lib/llvm/17/lib64/cmake/llvm
```
So adding version in `find_package` could help, but it is not the only solution.

**Comment by emankov** [comment]
OK, thanks for your response!

> So adding version in find_package could help, but it is not the only solution.

We can't stick with a particular version or a range while finding LLVM, as older versions may be installed depending on the user's platform. Choosing the latest version `by default` is a common and generally accepted behaviour of `find_package`; otherwise, the user must explicitly specify the needed version.

**Comment by AngryLoki** [comment]
After thinking a bit more, I agree with you. At any point of time you can't control, in which next LLVM release compatibility will be broken and in the past won't be able to release HIPIFY in rocm-5.7.1 with `find_package(LLVM 17 REQUIRED)`, as you can't say now that current version will be compatible only with LLVM 19 (and not LLVM 20).
