### ISSUE TITLE
[HIPIFY][perl] Suppress warnings in prepr's false conditional branches

### ISSUE THREAD

**Issue by acowley** [ROCm-Developer-Tools/HIPIFY#154]
Let me preface this by acknowledging that most development effort is behind hipify-clang, so I accept an answer of: "You have to use hipify-clang." 😄

I have been a happy hipify-perl user for quite a long time, as installing the CUDA SDK on my AMD targets is something I'd like to avoid. A minor issue I have is that I can have a CUDA source file that branches with something like,

```C
#ifdef __HIP__
```

But if, in the `#else` of such a conditional , I mention a CUDA API that hipify-perl does not support, then I get a warning. Is it possible to have a guard around some code such that hipify-perl will just let it through unchanged?

I'm imagining something like clang-format's `// clang-format off` toggle.

Thank you for your work on hipify!

**Comment by emankov** [comment]
Am I right that you want to suppress warnings on the particular unsupported CUDA entities?

**Comment by acowley** [comment]
Yes, exactly. They are in a guarded region that switches based on if the compiler is hip or nvcc, so I am sort of manually hipify-ing that code.

**Comment by emankov** [comment]
So you need a preprocessing, and not for a transformation but for a suppressing of warnings. Hmm. You want more than too much from a perl script, don't you?

Preprocessing is not implemented in hipify-perl as long as macros expansion, so, yes, you need hipify-clang.
