### ISSUE TITLE
[HIPIFY][build][Issue] std::__throw_bad_array_new_length build failure on Red Hat Enterprise Linux Server release 7.9

### ISSUE THREAD

**Issue by AnwarXahid** [ROCm-Developer-Tools/HIPIFY#1586]
I was trying to install **hipify-clang** using the following commands:
 
_git clone https://github.com/ROCm/HIPIFY.git hipify
cd hipify/.. 
mkdir build dist
cd build
cmake -DCMAKE_INSTALL_PREFIX=../dist DCMAKE_BUILD_TYPE=Release ../hipify
make -j install_
 
Everything went fine, until, at the last step while the linker is evoked; I got this error:
 
_undefined references to `**std::__throw_bad_array_new_length()**' follow
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:698: hipify-clang] Error 1
make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/hipify-clang.dir/all] Error 2
make: *** [Makefile:149: all] Error 2_
 
My **LLVM+Clang** version: 16.0.6
**CUDA** version: 11.2.0
**GCC** version: 8.3.1
**cmake** version: 3.18.0

Why I'm getting this error? What might be wrong?

**Comment by emankov** [comment]
Hi @AnwarXahid,

Could you use the newer GCC version, please? 8.x is already out of our (and LLVM's) support. Compilation should work correctly with GCC 9.2 or higher. Thanks!

https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-clang.rst#linux-testing:
> Minimum build system requirements for the above configurations:
CMake 3.16.8, GNU C/C++ 9.2, Python 3.0.

**Comment by AnwarXahid** [comment]
Yeah. It worked. Thanks!
