### ISSUE TITLE
[HIPIFY] quick start questions on hipify-clang

### ISSUE THREAD

**Issue by ZJLi2013** [ROCm-Developer-Tools/HIPIFY#1604]
### Problem Description

Hi, I am pretty new to hipify-clang tool. I am trying to porting a cuda based project to rocm(hip) project.  
as rocm-pytorch image has provided `hipify-clang` by default, so I'd thought `hipify-clang` can work in rocm-pytorch images.

while during usage, it always complain:
```yml
error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
``` 
so  looks `hipify-clang` requires a `cuda environment`.  so  a few questions in mind:

1) what's the usage case for `hipify-clang` in a rocm-pytorch image?
2) Does it mean, for porting existing cuda project to rocm, user need to build hipify from source in an CUDA environment first, as cuda docker doesn't provide pre-built hipify tool?

Thanks for quick answer
David   

### Operating System

ubuntu 20.04

### CPU

Intel(R) Xeon(R) Platinum 8480C

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
Hello @ZJLi2013,

> 1. what's the usage case for hipify-clang in a rocm-pytorch image?

Please address this question to https://github.com/ROCm/hipify_torch.

> 2. Does it mean, for porting existing cuda project to rocm, user need to build hipify from source in an CUDA environment first, as cuda docker doesn't provide pre-built hipify tool?

Nope, users can install the corresponding ROCm package with HIPIFY tools (hipify-clang + hipify-perl). hipify-clang needs CUDA installed in the system, whereas hipify-perl doesn't.

Please, refer to the documentation for the details:
https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-clang.rst
https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/hipify-perl.rst

**Comment by emankov** [comment]
Closing as answered.
