### ISSUE TITLE
[HIPIFY][feature] Support for `fp8` data types

### ISSUE THREAD

**Issue by foreverlms** [ROCm-Developer-Tools/HIPIFY#1617]
### Problem Description

Such as when I hipify a cu file  having fp8 datatype in it, after the `hipify-clang` command, the fp8 datatype doesn't turned into HIP fp8 type.

For example:

```
__nv_fp8_e4m3
```
doesn't change and the `hipify-clang` will report error:

```
 error: unknown type name '__nv_fp8_e4m3'
```

Why? Doesn't hipify support FP8?

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa)

### CPU

 AMD EPYC 7643 48-Core Processor

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
Hello @foreverlms,

Currently, HIP supports some of the `fp8` data types and APIs. Whereas, HIPIFY tools don't. Thank you for pointing it out.

Marking the ticket as a `feature` to Implement.

**Comment by foreverlms** [comment]
Thanks for replying. Hope to see the fp8 support available.

**Comment by emankov** [comment]
Finally implemented.

**Comment by emankov** [comment]
> Thanks for replying. Hope to see the fp8 support available.

Hi @foreverlms,
 
It is available now. Going to revise fp16 soon.

**Comment by foreverlms** [comment]
> > Thanks for replying. Hope to see the fp8 support available.
> 
> Hi @foreverlms,
> 
> It is available now. Going to revise fp16 soon.

Thanks, this could be very helpful for mix300 series.
