### ISSUE TITLE
[HIPIFY][MIOpen][feature] Support backend graphAPI for translating from cuDNN to MIOpen directly. 

### ISSUE THREAD

**Issue by BrianHarrisonAMD** [ROCm-Developer-Tools/HIPIFY#1624]
### Problem Description

Requesting support to HIPIFY directly from cuDNN to MIOpen for a subset of the backend GraphAPI methods and types.

Here is a file that has the types and functions that need to support translation for the backend API:
- https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_shim.h

Types list:
- cudnnTensorFormat_t -> miopenTensorLayout_t
- For all backend types:
    - cudnnBackendX_t -> miopenBackendX_t
    - cudnnBackendXType_t -> miopenBackendXType_t 
    - CUDNN_BACKEND_X_DESCRIPTOR -> MIOPEN_BACKEND_X_DESCRIPTOR

Functions List:
- cudnnBackendCreateDescriptor -> miopenBackendCreateDescriptor 
- cudnnBackendDestroyDescriptor -> miopenBackendDestroyDescriptor
- cudnnBackendInitialize -> miopenBackendInitialize 
- cudnnBackendFinalize -> miopenBackendInitialize 
- cudnnBackendSetAttribute -> miopenBackendSetAttribute
- cudnnBackendGetAttribute -> miopenBackendGetAttribute 
- cudnnBackendExecute -> miopenBackendExecute

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa) or Ubuntu 22.04.4 LTS  (Jammy Jellyfish)

### CPU

Any

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
`cudnnBackendInitialize` -> `miopenBackendInitialize`:

The functions have different signatures:

```c++
CUDNN_DEPRECATED cudnnStatus_t CUDNNWINAPI
cudnnBackendInitialize(cudnnBackendDescriptor_t descriptor);
```

```c++
MIOPEN_EXPORT miopenStatus_t miopenBackendInitialize(miopenBackendDescriptor_t descriptor,
                                                     miopenBackendDescriptorType_t descriptorType,
                                                     size_t sizeInBytes);
```
There are two options here:
**1.** [MIOpen team] To provide the default values for arguments `descriptorType` and `sizeInBytes`.
**2.** [MIOpen team] To provide yet another function - `miopenBackendInitialize` with the same signature as `cudnnBackendInitialize`

@BrianHarrisonAMD, what do you prefer, or are there might be other options on the list?

**Comment by BrianHarrisonAMD** [comment]
LGTM!

Thanks!
