### ISSUE TITLE
[HIPIFY][perl][MIOpen][feature] Add--miopen option for hipify-perl

### ISSUE THREAD

**Issue by BrianHarrisonAMD** [ROCm-Developer-Tools/HIPIFY#1625]
### Problem Description

Currently hipify-clang supports going directly to MIOpen via the argument --miopen.
hipify-perl on the other hand, seems to not support this same option.

This request is to have the same option added to hipify-perl. 

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa) or Ubuntu 22.04.4 LTS (Jammy Jellyfish)

### CPU

Any

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
Implemented by #1779
