### ISSUE TITLE
[HIPIFY][Issue] Must define exactly one of `__HIP_PLATFORM_AMD__` or `__HIP_PLATFORM_NVIDIA__`

### ISSUE THREAD

**Issue by foreverlms** [ROCm-Developer-Tools/HIPIFY#1643]
### Problem Description

If I hipify a file already contains hip c++, for example:

```c++
#ifndef __HIP_PLATFORM_AMD__
#include <cub/cub.cuh>
#else
#include <hipcub/hipcub.hpp>
#endif
```

When I hipify this file, I will pass the `-D__HIP_PLATFORM_AMD__` to hipify-clang. But error happens:

```
In file included from /opt/rocm/include/hipcub/hipcub.hpp:31:
In file included from /opt/rocm/include/hipcub/config.hpp:47:
In file included from /opt/rocm/include/rocprim/device/config_types.hpp:31:
In file included from /opt/rocm/include/rocprim/device/../config.hpp:34:
/opt/rocm/include/hip/hip_bfloat16.h:41:2: error: ("Must define exactly one of __HIP_PLATFORM_AMD__ or __HIP_PLATFORM_NVIDIA__");
   41 | #error("Must define exactly one of __HIP_PLATFORM_AMD__ or __HIP_PLATFORM_NVIDIA__");
```
and:
```
In file included from /opt/rocm/include/hipcub/hipcub.hpp:31:
In file included from /opt/rocm/include/hipcub/config.hpp:47:
/opt/rocm/include/rocprim/device/config_types.hpp:308:31: error: use of undeclared identifier 'hipGetDevicePropertiesR0600'; did you mean 'cudaGetDeviceProperties_v2'?
  308 |     const hipError_t result = hipGetDeviceProperties(&device_props, device_id);
      |                               ^~~~~~~~~~~~~~~~~~~~~~
      |                               cudaGetDeviceProperties_v2
/opt/rocm/include/hip/hip_runtime_api.h:91:32: note: expanded from macro 'hipGetDeviceProperties'
   91 | #define hipGetDeviceProperties hipGetDevicePropertiesR0600
      |                                ^
/usr/local/cuda/include/cuda_runtime_api.h:1722:58: note: 'cudaGetDeviceProperties_v2' declared here
 1722 | extern __host__ __cudart_builtin__ cudaError_t CUDARTAPI cudaGetDeviceProperties(struct cudaDeviceProp *prop, int device);
      |                                                          ^
/usr/local/cuda/include/cuda_runtime_api.h:170:33: note: expanded from macro 'cudaGetDeviceProperties'
```

Seems this predefined macro `__HIP_PLATFORM_AMD__` was lost when parsing hip core libs?

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa)

### CPU

 AMD EPYC 7643 48-Core Processor

### ROCm Version

ROCm 6.0.0

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
Hello @foreverlms,

May I ask why do you need to hipify the code already containing HIP code?

**Comment by foreverlms** [comment]
> Hello @foreverlms,
> 
> May I ask why do you need to hipify the code already containing HIP code?

It's mixed with cuda and hip. controlled by macros. But most of them are cuda. So for the cuda part, I still need to hipify them.

**Comment by emankov** [comment]
Hipifying of the mixed code is not what HIPIFY tools are designed for, for at least hipify-clang, which is being a compiler, in fact, gets a CUDA code as a source and compiles it always with `-x cu`. When you are passing `-D__HIP_PLATFORM_AMD__`, you try to force the compiler to compile `HIP` and get the error `Must define exactly one of __HIP_PLATFORM_AMD__ or __HIP_PLATFORM_NVIDIA__`

Btw, there is still a strategy for the opposite thing on the table to implement - hipifying to the "mixed" code by making the CUDA source codes CUDA or HIP in a single source depending on the preprocessor define (#536). And it looks like you already have such a code.

So, I have two options for you.
**Option 1.** Please share your code snippet with such a mix, and I'll try to think about how to deal with it by hipify-clang.
**Option 2.** Try to use `hipify-perl` instead.

**Comment by emankov** [comment]
Hi @foreverlms,

So what about the option you chose? Anyway, it would be great to deal with your snippet.

**Comment by foreverlms** [comment]
> Hi @foreverlms,
> 
> So what about the option you chose? Anyway, it would be great to deal with your snippet.

Thanks for your suggestion! I have bypassed this by removing the mix part. Keepping only the cuda way and let hipify-clang to handle it completely.
So my problem is solved, for the mixed HIP and CUDA sources, I think we could close this issue, if anyone else has the same problem, this issue could be reopened.
