### ISSUE TITLE
[HIPIFY] Question: mismatching info about hipify 6.2.2 release versions support..

### ISSUE THREAD

**Issue by oscarbg** [ROCm-Developer-Tools/HIPIFY#1679]
### Problem Description

changelog file (https://github.com/ROCm/HIPIFY/blob/amd-staging/CHANGELOG.md) mentions things like cuDNN 9.3.0 support but :
```
HIPIFY for ROCm 6.2.2
Additions

    cuDNN 9.3.0 support

Fixes

    Removed some post HIP 6.2 APIs from support
    Added hipification support for HIP functions hipSetValidDevices, hipMemcpy2DArrayToArray, hipMemcpyAtoA, hipMemcpyAtoD, hipMemcpyAtoA, hipMemcpyAtoHAsync, and hipMemcpyHtoAAsync
    Fixed an issue with Skipped some replacements when hipification didn't occur at all

```
but
> https://github.com/ROCm/HIPIFY/releases/tag/rocm-6.2.2

mentions no changes:

>HIPIFY code for ROCm 6.2.2 did not change

what is correct?
are 6.2.2 changes delayed to 6.2.3?
thanks..

### Operating System

ubu

### CPU

ryzen

### ROCm Component

HIPIFY

**Comment by emankov** [comment]
The `6.2.2` changes are going to appear in `6.2.4`. Thanks for your observation. The Changelog is fixed.
