### ISSUE TITLE
[HIPIFY] Texture Memory of CUDA

### ISSUE THREAD

**Issue by HWang-Summit** [ROCm-Developer-Tools/HIPIFY#222]
In my CUDA version, I used texture memory, but when I used HIPIFY conversion, the following problems occurred. Is it because HIP does not support texture memory? Do I need to remove or modify the texture memory before conversion?

warning: Unknown CUDA version 11.0. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
/tmp/gridding.cu-6a50d3.hip:421:18: **warning: CUDA identifier is deprecated.**
    HANDLE_ERROR(cudaBindTexture(NULL, tex_start_ring, d_start_ring, sizeof(uint32_t)*(usedrings+1)));
                 ^
/tmp/gridding.cu-6a50d3.hip:475:19: **warning: CUDA identifier is deprecated.**
    HANDLE_ERROR( cudaUnbindTexture(tex_start_ring) );

/tmp/gridding.cu-6a50d3.hip:326:30: ****error:** no matching function for call to 'tex1Dfetch'**
        uint32_t start_int = tex1Dfetch(tex_start_ring, uring-d_const_Healpix.firstring);
                             ^~~~~~~~~~
/usr/local/cuda-11.0/include/texture_indirect_functions.h:112:21: **note: candidate template ignored: couldn't infer template argument 'T'**
static __device__ T tex1Dfetch(cudaTextureObject_t texObject, int x)
                    ^
/usr/local/cuda-11.0/include/texture_indirect_functions.h:104:53: note: candidate function template not viable: requires 3 arguments, but 2 were provided
static __device__ typename __nv_itex_trait<T>::type tex1Dfetch(T *ptr, cudaTextureObject_t obj, int x)
                                                    ^
/tmp/gridding.cu-6a50d3.hip:329:32: ****error:** no matching function for call to 'tex1Dfetch'**
            uint32_t end_int = tex1Dfetch(tex_start_ring, uring-d_const_Healpix.firstring+1);
                               ^~~~~~~~~~
/usr/local/cuda-11.0/include/texture_indirect_functions.h:112:21: note: candidate template ignored: couldn't infer template argument 'T'
static __device__ T tex1Dfetch(cudaTextureObject_t texObject, int x)
                    ^
/usr/local/cuda-11.0/include/texture_indirect_functions.h:104:53: note: candidate function template not viable: requires 3 arguments, but 2 were provided
static __device__ typename __nv_itex_trait<T>::type tex1Dfetch(T *ptr, cudaTextureObject_t obj, int x)
                                                    ^
/tmp/gridding.cu-6a50d3.hip:421:18: warning: 'cudaBindTexture<unsigned int, 1, cudaReadModeElementType>' is deprecated [-Wdeprecated-declarations]
    HANDLE_ERROR(cudaBindTexture(NULL, tex_start_ring, d_start_ring, sizeof(uint32_t)*(usedrings+1)));
                 ^
/usr/local/cuda-11.0/include/cuda_runtime.h:982:8: **note: 'cudaBindTexture<unsigned int, 1, cudaReadModeElementType>' has been explicitly marked deprecated here**
static __CUDA_DEPRECATED __inline__ __host__ cudaError_t cudaBindTexture(
       ^
/usr/local/cuda-11.0/include/cuda_runtime.h:138:42: note: expanded from macro '__CUDA_DEPRECATED'
#define __CUDA_DEPRECATED __attribute__((deprecated))
                                         ^
/tmp/gridding.cu-6a50d3.hip:475:19: **warning: 'cudaUnbindTexture<unsigned int, 1, cudaReadModeElementType>' is deprecated [-Wdeprecated-declarations]**
    HANDLE_ERROR( cudaUnbindTexture(tex_start_ring) );
                  ^
/usr/local/cuda-11.0/include/cuda_runtime.h:1304:8: note: 'cudaUnbindTexture<unsigned int, 1, cudaReadModeElementType>' has been explicitly marked deprecated here
static __CUDA_DEPRECATED __inline__ __host__ cudaError_t cudaUnbindTexture(
       ^
/usr/local/cuda-11.0/include/cuda_runtime.h:138:42: note: expanded from macro '__CUDA_DEPRECATED'
#define __CUDA_DEPRECATED __attribute__((deprecated))

**Comment by emankov** [comment]
Could you provide your source file(s), please?

**Comment by HWang-Summit** [comment]
Thank you for your reply!  Please see the source code in the attachment.
And “https://github.com/HWang-Summit/HCGrid” is the entire project code
that I want to convert.

Evgeny Mankov <notifications@github.com> 于2020年11月16日周一 下午6:26写道：

**Comment by HWang-Summit** [comment]
Do you have any constructive suggestions on this issue?  Thank you.

hao wang <h.wang.imu@gmail.com> 于2020年11月17日周二 上午9:36写道：

**Comment by emankov** [comment]
How do you compile it by nvcc? Is it compiled successfully by nvcc?

**Comment by emankov** [comment]
It looks like an erroneous usage of the function `tex1Dfetch`:
```c++
template <typename T>
static __forceinline__ __device__ typename __nv_tex_rmnf_ret<T>::type tex1Dfetch(texture<T, cudaTextureType1D, cudaReadModeNormalizedFloat> t, int x) 
```
Its first argument should be of `texture<T, cudaTextureType1D, cudaReadModeElementType>` type, but you declared it simply like `texture<uint32_t> tex_start_ring;`

So, I see two options here for you:
1. Fix the usage of `tex1Dfetch`.
2. Comment your two usages of `tex1Dfetch` (uint32_t start_int = 0, uint32_t end_int = 1, for instance) and then hipify `gridding.cu`. I did it myself: the hipified file is attached: [gridding.zip](https://github.com/ROCm-Developer-Tools/HIPIFY/files/5617056/gridding.zip).

**Comment by emankov** [comment]
Close as answered.
