### ISSUE TITLE
[HIPIFY] Thrust of CUDA 

### ISSUE THREAD

**Issue by HWang-Summit** [ROCm-Developer-Tools/HIPIFY#223]
In my CUDA version, I used Thrust Library, and Saw the ROCm platform overwritten it to HIP. However, during the HIPIFY conversion, did I need to download Thrust from ROCm to replace it in my current program and then convert my project? The following error occurred during the conversion without any changes:

In file included from /tmp/gridding.cu-6a50d3.hip:37:
In file included from /usr/local/cuda-11.0/include/thrust/sort.h:1361:
In file included from /usr/local/cuda-11.0/include/thrust/detail/sort.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/sort.h:153:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/sort.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/find.h:384:
In file included from /usr/local/cuda-11.0/include/thrust/detail/find.inl:25:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/find.h:62:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/find.inl:19:
In file included from /usr/local/cuda-11.0/include/thrust/reduce.h:784:
In file included from /usr/local/cuda-11.0/include/thrust/detail/reduce.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/reduce_by_key.h:88:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/reduce_by_key.inl:29:
In file included from /usr/local/cuda-11.0/include/thrust/transform.h:724:
In file included from /usr/local/cuda-11.0/include/thrust/detail/transform.inl:25:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/transform.h:105:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/transform.inl:19:
In file included from /usr/local/cuda-11.0/include/thrust/for_each.h:279:
In file included from /usr/local/cuda-11.0/include/thrust/detail/for_each.inl:27:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/adl/for_each.h:42:
In file included from /usr/local/cuda-11.0/include/thrust/system/cuda/detail/for_each.h:35:
In file included from /usr/local/cuda-11.0/include/thrust/system/cuda/detail/parallel_for.h:36:
/usr/local/cuda-11.0/include/thrust/system/cuda/detail/core/agent_launcher.h:562:11: error: use of undeclared identifier 'va_printf'
          _CubLog("Invoking %s<<<%u, %d, %d, %lld>>>(), %llu items total, %d items per thread, %d SM occupancy, %d vshmem size, %d ptx_version \n",
          ^
/usr/local/cuda-11.0/include/cub/util_debug.cuh:149:42: note: expanded from macro '_CubLog'
            #define _CubLog(format, ...) va_printf(format,__VA_ARGS__);
                                         ^
In file included from /tmp/gridding.cu-6a50d3.hip:37:
In file included from /usr/local/cuda-11.0/include/thrust/sort.h:1361:
In file included from /usr/local/cuda-11.0/include/thrust/detail/sort.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/sort.h:153:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/sort.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/find.h:384:
In file included from /usr/local/cuda-11.0/include/thrust/detail/find.inl:25:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/find.h:62:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/find.inl:19:
In file included from /usr/local/cuda-11.0/include/thrust/reduce.h:784:
In file included from /usr/local/cuda-11.0/include/thrust/detail/reduce.inl:26:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/reduce_by_key.h:88:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/reduce_by_key.inl:29:
In file included from /usr/local/cuda-11.0/include/thrust/transform.h:724:
In file included from /usr/local/cuda-11.0/include/thrust/detail/transform.inl:25:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/transform.h:105:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/generic/transform.inl:19:
In file included from /usr/local/cuda-11.0/include/thrust/for_each.h:279:
In file included from /usr/local/cuda-11.0/include/thrust/detail/for_each.inl:27:
In file included from /usr/local/cuda-11.0/include/thrust/system/detail/adl/for_each.h:42:
In file included from /usr/local/cuda-11.0/include/thrust/system/cuda/detail/for_each.h:35:
In file included from /usr/local/cuda-11.0/include/thrust/system/cuda/detail/parallel_for.h:36:
/usr/local/cuda-11.0/include/thrust/system/cuda/detail/core/agent_launcher.h:576:11: error: use of undeclared identifier 'va_printf'
          _CubLog("Invoking %s<<<%u, %d, %d, %lld>>>(), %d items per thread, %d SM occupancy, %d vshmem size, %d ptx_version\n",
          ^
/usr/local/cuda-11.0/include/cub/util_debug.cuh:149:42: note: expanded from macro '_CubLog'
            #define _CubLog(format, ...) va_printf(format,__VA_ARGS__);

**Comment by emankov** [comment]
Could you provide your CUDA source file(s), please?

**Comment by HWang-Summit** [comment]
Thank you for your reply!  Please see the source code in the attachment.
And “https://github.com/HWang-Summit/HCGrid” is the entire project code
that I want to convert.

Evgeny Mankov <notifications@github.com> 于2020年11月16日周一 下午6:23写道：

**Comment by HWang-Summit** [comment]
Do you have any constructive suggestions on this issue?  Thank you.

hao wang <h.wang.imu@gmail.com> 于2020年11月17日周二 上午9:33写道：

**Comment by emankov** [comment]
`gridding.cu` was successfully hipified on my side. Please, see the resulted .hip file: [gridding.hip](https://github.com/ROCm-Developer-Tools/HIPIFY/files/5617056/gridding.zip).

**Comment by HWang-Summit** [comment]
Thank you!

Evgeny Mankov <notifications@github.com> 于2020年12月1日周二 上午12:09写道：

**Comment by emankov** [comment]
Closed as answered.
