### ISSUE TITLE
[HIPIFY] gemmi supported by hipSPARSE but not HIPIFY

### ISSUE THREAD

**Issue by paravoid** [ROCm-Developer-Tools/HIPIFY#228]
gemmi (e.g. hipsparseSgemmi) is supported by hipSPARSE since 3.7.0, cf.
https://github.com/ROCmSoftwarePlatform/hipSPARSE/commit/4bebd276ee09d46f9448283337677ff12e351497. However, HIPIFY still shows this as HIP_UNSUPPORTED. Is that an omission?

**Comment by emankov** [comment]
Will be fixed during a week. Thanks.

**Comment by emankov** [comment]
Done by #230.
