### ISSUE TITLE
[HIPIFY][perl][feature request] Specify output file as a cli parameter

### ISSUE THREAD

**Issue by mconcas** [ROCm-Developer-Tools/HIPIFY#268]
Cheers,

Would be nice to have the possibility to specify the output file of the `hipify-perl`command.
This is useful In those cases I want to generate on-the-fly a translation without involving a shell or at least not involving pipe redirections.
An example is the `execute_process()`(*) CMake command.
Of course, for that case a workaround is to invoke the shell command `/bin/sh -c "...."`.
Is it possible that I had missed the feature (perhaps CMake spefici too)? Or we cannot avoid to pass through a shell because of the environment?

Thanks in advance

(*) E.g. [execute_process](https://cmake.org/cmake/help/latest/command/execute_process.html)

**Comment by emankov** [comment]
Implemented by #298
