### ISSUE TITLE
[HIPIFY] hipify-clang ignoring `#if-#else-#endif` preprocessor directives?

### ISSUE THREAD

**Issue by rosenrodt** [ROCm-Developer-Tools/HIPIFY#348]
I have code snippet like this:
```c++
// platform.h
#if defined(__CUDACC_RTC__) || (!defined(_MSC_VER) && (__cplusplus < 201103L)) || (defined(_MSC_VER) && (_MSC_VER < 1600))
  #pragma message( ">>>>>>>>>>>>C Preprocessor got here (1)!" )
#else
  #pragma message( ">>>>>>>>>>>>C Preprocessor got here (2)!" )
#endif
```

And when I feed that into hipify-clang:
```log
$ hipify-clang platform.h --cuda-path=/usr/local/cuda-11.3 --cuda-gpu-arch=sm_75 -- -std=c++17 -x cuda
/tmp/platform.h-734707.hip:316:9: warning: >>>>>>>>>>>>C Preprocessor got here (1)! [-W#pragma-messages]
#pragma message( ">>>>>>>>>>>>C Preprocessor got here (1)!" )
        ^
/tmp/platform.h-734707.hip:340:9: warning: >>>>>>>>>>>>C Preprocessor got here (2)! [-W#pragma-messages]
#pragma message( ">>>>>>>>>>>>C Preprocessor got here (2)!" )
        ^
```

Is this an expected behavior for hipify-clang to ignore the if-else-endif preprocessor directives? This code is meant to define the missing structs if there's lack of compiler support. If hipify-clang ignores those directives, a declaration conflict would occur therefore it fails to hipify. Hence I wonder if this is by design or I overlooked something?

**Comment by emankov** [comment]
Duplicate of [#281](https://github.com/ROCm-Developer-Tools/HIPIFY/issues/281).

**Comment by rosenrodt** [comment]
> Duplicate of [#281](https://github.com/ROCm-Developer-Tools/HIPIFY/issues/281).

Looks worthy or trying. Thanks!

Closing issue
