### ISSUE TITLE
[HIPIFY] cudaHostAlloc and cudaMallocHost are incorrectly mapped

### ISSUE THREAD

**Issue by emankov** [ROCm-Developer-Tools/HIPIFY#349]
Currently, they both are mapped to `hipHostMalloc` but should be mapped to HIP deprecated, but still working `hipHostAlloc` and `hipMallocHost`. Moreover, `hipHostMalloc` and `cudaHostAlloc/cudaMallocHost` have different signatures.

**Comment by emankov** [comment]
Fixed with #356

**Comment by jakub329homola** [comment]
Can I ask, why should these two host allocation functions be mapped to the two **deprecated** HIP functions instead of _hipHostMalloc_? Why was the previous behaviour incorrect? To me it does not make sense.

**Comment by emankov** [comment]
1. The deprecated HIP functions are still being used; they are just marked as deprecated.
2. `hipHostMalloc` and `cudaHostAlloc/cudaMallocHost` have different signatures; thus, previous mappings were simply incorrect.
