### ISSUE TITLE
[HIPIFY] transformExternShared no longer required

### ISSUE THREAD

**Issue by mangupta** [ROCm-Developer-Tools/HIPIFY#374]
Since hip-clang now supports extern shared similar to CUDA, we don't need the HIP_DYNAMIC_SHARED wrapper and calling the transformExternShared() call in hipify-perl. Something similar is probably needed in hipify-clang as well. This was manually removed from hipify-perl (when it should not have been) in hip repo via https://github.com/ROCm-Developer-Tools/HIP/commit/090b2829b9a4ee3c55ef71a82a1d103c0a9cdd36#diff-afb4c89e68eec60303b0b2bacbb9199df0d63991392f85123e4238cffb838bd3 and https://github.com/ROCm-Developer-Tools/HIP/commit/4af2e3d87e4afab710f020b802dac17883cf4fa4#diff-afb4c89e68eec60303b0b2bacbb9199df0d63991392f85123e4238cffb838bd3.

**Comment by emankov** [comment]
Fixed with #375.
