### ISSUE TITLE
[HIPIFY][perl] Unsupported device function "mul24"

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIPIFY#498]
Hipify (i.e. hipconvertinplace-perl.sh) shows the message unsupported device function "mul24" when converting a CUDA program. but __mul24 is supported by HIP.

We may just ignore the warning.

Thanks.

**Comment by zjin-lcf** [comment]
We may just ignore the warning.

**Comment by emankov** [comment]
Fixed with #567.
