### ISSUE TITLE
[HIPIFY][perl] Why don't hipify-perl migrate cublasGemm* to rocblasGemm*?

### ISSUE THREAD

**Issue by lingjiew93** [ROCm-Developer-Tools/HIPIFY#500]
Hi,
I'm trying to migrate some gemm example from cuda to hip.
hipify-perl migrate cublas to hipblas, and hipblas was an experimental BLAS implementation for ROCm and has been DEPRECATED. 
That means one must use the hipblas library for the migrated code.
Is there a easy way to use rocblas with migration?

**Comment by emankov** [comment]
Hi @lingjiew93,

You can try `hipify-clang` with the `--roc` option to translate `cuBLAS` to `rocBLAS`. Unfortunately, it is not yet implemented in the `hipify-perl` tool. I'll add a corresponding feature request for implementing the `--roc` option in `hipify-perl` too.

**Comment by lingjiew93** [comment]
Thanks for your quick reply.
