### ISSUE TITLE
[HIPIFY][perl] Unsupported device function int_as_float/float_as_int

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIPIFY#501]
Hipify (i.e. hipconvertinplace-perl.sh) shows the message unsupported device function "int_as_float"/"float_as_int" when converting a CUDA program. but __int_as_float/__float_as_int are supported by HIP.

We may just ignore the warning.

Thanks.

**Comment by emankov** [comment]
Duplicate of #498.

**Comment by emankov** [comment]
Fixed with #567.
