### ISSUE TITLE
[HIPIFY] hipify-perl binary not found on 5.0.1 pytorch docker image

### ISSUE THREAD

**Issue by baijumeswani** [ROCm-Developer-Tools/HIPIFY#511]
Using the docker image `rocm5.0.1_ubuntu18.04_py3.7_pytorch_staging`, I am unable to locate the hipify binaries `hipify-perl` in the directory `/opt/rocm/hip/bin/`.

Was the location of the binary moved?

**Comment by emankov** [comment]
@aakanksha555, could you please guide on how to install HIPIFY tools package fro Ubuntu?

**Comment by aakanksha555** [comment]
If you have a hipify package just installing it like any other debian package will work. (dpkg -i package_name.deb)
If you want to create a package you need to first build hipify project and then "make package_hipify-clang".
The package install location is determined by CPACK_PACKAGING_INSTALL_PREFIX or by default it installs to "/opt/rocm/hip"

**Comment by emankov** [comment]
Close as answered.
