### ISSUE TITLE
[HIPIFY][build] CMake Error: The source directory "/home/mycode/HIPIFY/hipify" does not exist.

### ISSUE THREAD

**Issue by Liu-xiandong** [ROCm-Developer-Tools/HIPIFY#600]
When I wanted to build the hipify, I followed the README.md and cmake it. But in first step, I get the error.
My terminal show:
```
cmake -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_BUILD_TYPE=Release ../hipify
```
And I get the error message:
```
CMake Error: The source directory "/home/mycode/HIPIFY/hipify" does not exist.
```
 Please help me, thank you.

**Comment by emankov** [comment]
Please, follow the instruction: https://github.com/ROCm-Developer-Tools/HIPIFY#-hipify-clang-building, supposing that the hipify sources are cloned to the `hipify` folder mentioned in the cmake command line.
