### ISSUE TITLE
[HIPIFY] we need the conditional compilation

### ISSUE THREAD

**Issue by ZenggangLiu** [ROCm-Developer-Tools/HIPIFY#621]
i am hipifying a test kernel, which has the following layout:

#if !defined(PRODUCTION)
#error XXXX
#endif

extern "C"
__global__ void vecAdd(float *a, float *b, float *c, int n)
{
    // Get our global thread ID
    int id = blockIdx.x*blockDim.x+threadIdx.x;
 
    // Make sure we do not go out of bounds
    if (id < n)
        c[id] = a[id] + b[id];
}

but the hipifiy can not handle this.
it just splits out "Error while processing..." then exits.
not hip file has been generated.
In this case, we also need preprocessor support during the hipifying.
but it just using the raw lexer.

**Comment by emankov** [comment]
hipify-clang processes the undefined preprocessor conditional blocks. The reason for this is to try to hipify AMAP. If you need the default C/C++ compiler behaviour use the `--skip-excluded-preprocessor-conditional-blocks` option. For the list of available options use the `--help` option.

Moreover, your code has a syntactical error here: `int id = blockIdx.xblockDim.x+threadIdx.x;`

If you need further assistance, please, provide an exact source code as an attachment.

**Comment by ZenggangLiu** [comment]
thanks a lot emankov,
that option fixes my issue
