### ISSUE TITLE
[HIPIFY] is it possible to hipify all included cuda header files in one go?

### ISSUE THREAD

**Issue by ZenggangLiu** [ROCm-Developer-Tools/HIPIFY#623]
I encountering a problem when hipify a CU file, which #include some other header files, which include a bunch of other header files like a cascade.
by the way, some headers are in the same folder as cu file, some are not.

it would be really neat, if hipify could process all relevant files in one go and output the hip files in one place.
I also don't really want to process that containing folder, because i just want to port one module each time.
This will make the porting feasible.

Thanks for any helps

**Comment by emankov** [comment]
What do you mean by `relevant files`? Include files might be CUDA Toolkit ones, the mixed files CUDA/HIP, or even system files. 

`hipify-clang` uses an approach of the `main file`: the file specified `explicitly` as the input source file is only hipified. It supports neither a total folder/subfolders transformation of source files nor all the included header files tree.

- You may specify multiple source CUDA files to hipify, including header files.
- You may use the `-p` option for specifying compile command database in JSON format (https://github.com/ROCm-Developer-Tools/HIPIFY#-hipify-clang-usage). [IMP NOTE] Only additional clang options (like -D, -I, etc.) can be specified in that file.
