### ISSUE TITLE
[HIPIFY][HIP][RTC] Support for JIT linker functions

### ISSUE THREAD

**Issue by ArturoBlas** [ROCm-Developer-Tools/HIPIFY#676]
Hi,

I would like to know whether there is a plan to support in the near or long term either some of all of the JIT linker functionality such as `cuLinkCreate`, `cuLinkAddData`, etc.? This is a fundamental part of some applications and can be a deal breaker when it comes to HIP adoption.

I found this issue at the HIP project but it's remained unanswered for quite some time. 

https://github.com/ROCm-Developer-Tools/HIP/issues/906

Thank you.

**Comment by emankov** [comment]
Since ROCm HIP 5.3.0 both functions are supported:
`cuLinkCreate` -> `hiprtcLinkCreate`
`cuLinkAddData` -> `hiprtcLinkAddData`

**Comment by ArturoBlas** [comment]
Thank you, I just saw you added [this](https://github.com/ROCm-Developer-Tools/HIPIFY/commit/56b780c15a3d46158bdd13a0894c1db4ddaab889) to the documentation just a couple of days ago but all I need should be there :)

Is there support for this on any current Windows drivers?

**Comment by emankov** [comment]
Nope, not a couple of days ago. Those functions were published as supported experimentally with 5.3.0 releases. Now they become regular.

Nope, Windows is still not officially supported by ROCm HIP. But follow the news ;)

**Comment by emankov** [comment]
Closing as answered.
