### ISSUE TITLE
[HIPIFY] hipify assembly

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIPIFY#731]
Could you suggest how to migrate the in-line assembly program with HIPify ? Thanks.

```
static __device__ __inline__ uint32_t __mysmid() {
    uint32_t smid;
    asm volatile("mov.u32 %0, %%smid;" : "=r"(smid));
    return smid;
}

int main() {
  return 0;
}
```

**Comment by emankov** [comment]
There are no plans to port ISA assembler codes in an automated mode currently. Device functions and intrinsics are portable automatically, asm codes aren't.

Another question is whether should we point to the user all the places in the source codes with inline assembler codes.

**Comment by zjin-lcf** [comment]
A webpage that lists the assembly codes that match the PTX codes for common use cases will be helpful.

**Comment by emankov** [comment]
Do you mean matching ASM opcodes similarly to the existing matching of Device and Host APIs?

**Comment by zjin-lcf** [comment]
Similar to the table that lists Cuda and Hip APIs.

**Comment by emankov** [comment]
Well, it won't be possible with the assemblers, cause the languages are different: not only opcodes but operands and their number. Moreover, in general, there is no even solid 1-to-1 correspondence for each particular opcode.

In other words, translation from CUDA ISA PTX to AMD GCN ISA is a quite different and very complicated task, which I believe couldn't be solved automatically and unambiguously, moreover, keeping in mind the performance...

**Comment by emankov** [comment]
What can be done (in the short term) is to inform the user of all inline assembler occurrences in the hipified code.
I'll put it on the ToDo list.

**Comment by zjin-lcf** [comment]
I see. Thanks.
