### ISSUE TITLE
[HIPIFY][doc] Move porting guides from HIP docs

### ISSUE THREAD

**Issue by Maetveis** [ROCm-Developer-Tools/HIPIFY#817]
The HIP porting guide and HIP Kernel porting guide would have a better place next to the hipify documentation, currently it is hosted with the HIP documentation.

cc: @saadrahim

**Comment by emankov** [comment]
@Maetveis, 
I did not get how your ask was related to the HIPIFY repo in GitHub.

**Comment by emankov** [comment]
@saadrahim, any ideas?

**Comment by emankov** [comment]
@saadrahim, just a gentle reminder. Could you let us know if you will move the mentioned docs or do we have some concerns?
