### ISSUE TITLE
[HIPIFY] File extension '.C' recognition

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/HIPIFY#84]
It seems that the file extension '.C' is not recognized by the hip toolchain to examine the CUDA APIs.

**Comment by zjin-lcf** [comment]
Sorry I didn't reply at that time.  For example,  hipconvertinplace-perl.sh couldn't recognize a file with '.C'.  It is '.C' not '.c'.

**Comment by emankov** [comment]
Uppercase file extensions recognition support is added (#242).
