### ISSUE TITLE
[HIPIFY] Multiple files in-place hipification issue

### ISSUE THREAD

**Issue by chinchoretej** [ROCm-Developer-Tools/HIPIFY#89]
After using hipconvertinplace-perl.sh command I'm getting following warning:
![warning](https://user-images.githubusercontent.com/47495669/68859146-ad7eed00-070c-11ea-8213-d8a79d36f59f.png)

According to my observation this is because of this following two functions:

template<class Scalar>
_global_
void cudaEncode(const uint maxbits,
           const Scalar* scalars,
           Word *stream,
           const uint3 dims,
           const int3 stride,
           const uint3 padded_dims,
           const uint tot_blocks) { Some commands written over here}
.
.
.
hipLaunchKernelGGL(cudaEncode<Scalar>, dim3(grid_size), dim3(block_size), 0, 0, maxbits,
     d_data,
     stream,
     dims,
     stride,
     my_pad,
     my_blocks);

Will you please tell me exactly what is the problem. Because of this warning, while testing the application I'm getting following error:
Error: Missing metadata for _global_ function

**Comment by emankov** [comment]
Answered, not a bug.
