### ISSUE TITLE
[HIPIFY] migrate thrust::cuda::par.on

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIPIFY#922]
I tried hipconvertinplace-perl.sh. Please advise how to migrate `thrust::cuda::par.on(stream)` .  Thanks.

**Comment by emankov** [comment]
Are you targeting rocThrust in your migration? Could you please provide your CUDA code snippet and to what HIP code snippet you wish to migrate?

**Comment by jinz2014** [comment]
Please search in the file  https://github.com/BioinfoSZU/CURC/blob/master/src/compress.cu

Thanks for your comments/suggestions.

**Comment by jinz2014** [comment]
https://github.com/ROCmSoftwarePlatform/rocThrust/issues/301#event-9784996513

**Comment by emankov** [comment]
`rocThrust` is not yet supported by HIPIFY tools. We are going to support it in the upcoming releases.
