### ISSUE TITLE
[HIPIFY][BLASLt][question] How to convert cublasLt's API to hipblasLt's

### ISSUE THREAD

**Issue by shaojiewang** [ROCm-Developer-Tools/HIPIFY#936]
We somehow using cublasLt to compute linear operation in modern language model like transformer. We know that in rocm there is a similar lib called hipblasLt. But hipify does not support a conversion from cublasLt to hipblasLt. Do you have a plan to do that?

**Comment by emankov** [comment]
Yes, it is on the list.

**Comment by shaojiewang** [comment]
> Yes, it is on the list.

Thanks. In which rocm version can it be delivered?

**Comment by emankov** [comment]
Most likely with ROCm 6.0.

**Comment by emankov** [comment]
`CUBLASLT` to `HIPBLASLT` support will be shipped with HIPIFY 6.1.

**Comment by emankov** [comment]
Postponed to 6.2.

**Comment by oscarbg** [comment]
+1

**Comment by jcao-ai** [comment]
@emankov Hi, is there any timeline for this 6.2 version ?

**Comment by emankov** [comment]
In HIPIFY tools, `hipblasLt` will appear in May.

**Comment by emankov** [comment]
Finally implemented by #1508
