### ISSUE TITLE
[HIPIFY] hipify installation Query

### ISSUE THREAD

**Issue by GowriShankarEAAS** [ROCm-Developer-Tools/HIPIFY#971]
Hi All,
i am looking for installation of the hipify (latest version), however i got stuck with build part. 
could you please provide step by step instructions, which help me to understand and install
Thank you
-Gowri Shankar

**Comment by emankov** [comment]
Hello @GowriShankarEAAS,

The building instruction is here: https://github.com/ROCm-Developer-Tools/HIPIFY/blob/amd-staging/docs/hipify-clang.md#hipify-clang-building.

Could you give more details on what went wrong on your side, please?

**Comment by GowriShankarEAAS** [comment]
when i am executing the cmake after repo download, following error is coming

:~/HIPIFY/build$ cmake  -DCMAKE_INSTALL_PREFIX=../dist  -DCMAKE_BUILD_TYPE=Release  ../hipify
CMake Error: The source directory "/home/gowrishankar_guttikonda/HIPIFY/hipify" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

:~/HIPIFY/build$ cmake  -DCMAKE_INSTALL_PREFIX=../dist  -DCMAKE_BUILD_TYPE=Release  ..
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/gowrishankar_guttikonda/HIPIFY/build/CMakeFiles/CMakeOutput.log".
See also "/home/gowrishankar_guttikonda/HIPIFY/build/CMakeFiles/CMakeError.log".


GCC -->

~/HIPIFY/build$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by emankov** [comment]
> :~/HIPIFY/build$ cmake -DCMAKE_INSTALL_PREFIX=../dist -DCMAKE_BUILD_TYPE=Release ../hipify
CMake Error: The source directory "/home/gowrishankar_guttikonda/HIPIFY/hipify" does not exist.

`/home/gowrishankar_guttikonda/HIPIFY/hipify` should contain hipify sources, in this folder should be hipify's `CMakeLists.txt`

**Comment by emankov** [comment]
Hello @GowriShankarEAAS,

Are you ok with closing this ticket as answered?

**Comment by GowriShankarEAAS** [comment]
sure Mankov. thank you very much for your help

Regards,
Gowri Shankar G

**Comment by emankov** [comment]
Closing as answered
