### ISSUE TITLE
[HIPIFY] unsupported identifier warnings

### ISSUE THREAD

**Issue by jinz2014** [ROCm-Developer-Tools/HIPIFY#994]
I tried to migrate the cuda example (https://github.com/Ending2015a/ICCG0_CUDA) with hipconvertinplace-perl.sh. 

Any suggestions on the unsupported identifier warnings ?  Thanks.

  
 warning: iccg_solver.h:20: unsupported identifier "cusparseMatDescr"
  warning: iccg_solver.h:21: unsupported identifier "cusparseMatDescr"

  warning: solver.cu:77: unsupported identifier "cusparseSpMatDescr"
  warning: solver.cu:81: unsupported identifier "cusparseDnVecDescr"
  warning: solver.cu:84: unsupported identifier "cusparseDnVecDescr"
  warning: solver.cu:87: unsupported identifier "cusparseDnVecDescr"
  warning: solver.cu:103: removed identifier "cusparseDcsric0" since CUDA 11.0
  warning: solver.cu:103: deprecated identifier "cusparseDcsric0" since CUDA 10.2
  warning: solver.cu:103: unsupported identifier "cusparseDcsric0"
  warning: solver.cu:113: removed identifier "cusparseDcsric0" since CUDA 11.0
  warning: solver.cu:113: deprecated identifier "cusparseDcsric0" since CUDA 10.2
  warning: solver.cu:113: unsupported identifier "cusparseDcsric0"
  warning: solver.cu:117: removed identifier "cusparseDcsric0" since CUDA 11.0
  warning: solver.cu:117: deprecated identifier "cusparseDcsric0" since CUDA 10.2
  warning: solver.cu:117: unsupported identifier "cusparseDcsric0"
  warning: solver.cu:121: unsupported identifier "csrsv2Info"

**Comment by emankov** [comment]
The warning `unsupported identifier` means that the identifier is not yet supported either by HIP API, ROC API, or corresponding ROCm HIP library. It might be function, define, or data type.

There is up-to-date information about supported/unsupported APIs: https://github.com/ROCm-Developer-Tools/HIPIFY/blob/amd-staging/docs/supported_apis.md#supported-cuda-apis

**Comment by jinz2014** [comment]
cusparseMatDescr is converted to hipsparseMatDescr by the translator. So the warning message may be confusing.

**Comment by jinz2014** [comment]
CUDA_R_32F => HIPBLAS_R_32F: 2

This is mapped to HIP_R_32F.

**Comment by emankov** [comment]
> cusparseMatDescr is converted to hipsparseMatDescr by the translator. So the warning message may be confusing.

What kind of translators is meant?

The `struct cusparseMatDescr` is not translated to `hipsparseMatDescr` by HIPIFY tools, only the `typedef struct cusparseMatDescr *cusparseMatDescr_t` is translated to `typedef void* hipsparseMatDescr_t`, as hipSPARSE doesn't have a declaration of `hipsparseMatDescr` or any other struct corresponding to `struct cusparseMatDescr`. Thus, `cusparseMatDescr` is reported as unsupported by HIP.

**Comment by emankov** [comment]
> CUDA_R_32F => HIPBLAS_R_32F: 2
> 
> This is mapped to HIP_R_32F.

Here you are right, `typedef enum cudaDataType_t` should be translated to the already presented in HIP `typedef enum hipDataType`, but `hipDataType` is not supported yet by all the HIP libraries. As for hipBLAS, there is a corresponding ticket https://github.com/ROCmSoftwarePlatform/hipBLAS/issues/366. Once it is fixed in hipBLAS, HIPIFY tools will be updated accordingly.

**Comment by jinz2014** [comment]
Thanks
